version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Expose Node.js app on port 3000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis on the default port
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
